DO $$
DECLARE SUPPORTLINECOUNTLEN INT;
DECLARE MONITORINGMESSAGESETTINGLEN INT;
DECLARE LEN124 INT;

BEGIN
EXECUTE 'SELECT LENGTH(VALUE) FROM im.SETTING WHERE ID = 70' INTO SUPPORTLINECOUNTLEN;
EXECUTE 'SELECT LENGTH(VALUE) FROM im.SETTING WHERE ID = 123' INTO MONITORINGMESSAGESETTINGLEN;
EXECUTE 'SELECT LENGTH(VALUE) FROM im.SETTING WHERE ID = 124' INTO LEN124;
IF SUPPORTLINECOUNTLEN != 1 THEN
	UPDATE im.SETTING SET VALUE = DECODE('0A', 'HEX') WHERE ID = 70;
END IF;

IF MONITORINGMESSAGESETTINGLEN IS NULL THEN
	INSERT INTO im.SETTING (ID, VALUE) VALUES ('123', (E'\xC\xC\xC\xC'::bytea));
END IF;

IF LEN124 IS NULL THEN
	INSERT INTO im.SETTING (ID, VALUE) VALUES ('124', (E'\xC\xC\xC\xC'::bytea));
END IF;
END $$;
