
CREATE TABLE IF NOT EXISTS im.it_asset_undisposed
(
	id uuid NOT NULL default(gen_random_uuid()),
	it_asset_import_setting_id uuid NOT NULL,
	detection_time timestamp NOT NULL,
	reason_code smallint NOT NULL,
	name CHARACTER VARYING(255) NULL,
	inv_number CHARACTER VARYING(50) NULL,
	serial_number CHARACTER VARYING(255) NULL,
	code CHARACTER VARYING(50) NULL,
	external_id CHARACTER VARYING(250) NULL,
	asset_tag CHARACTER VARYING(50) NULL,
	note CHARACTER VARYING(1000) NULL,
	description CHARACTER VARYING(250) NULL,
	type_external_id CHARACTER VARYING(50) NULL,
	type_name CHARACTER VARYING(500) NULL,
	model_external_id CHARACTER VARYING(250) NULL,
	model_name CHARACTER VARYING(255) NULL,
	vendor_external_id CHARACTER VARYING(250) NULL,
	vendor_name CHARACTER VARYING(255) NULL,
	supplier_external_id CHARACTER VARYING(250) NULL,
	supplier_name CHARACTER VARYING(255) NULL,
	owner_external_id CHARACTER VARYING(500) NULL,
	owner_name CHARACTER VARYING(255) NULL,
	utilizer_external_id CHARACTER VARYING(500) NULL,
	utilizer_name CHARACTER VARYING(255) NULL,
	equipment_external_id CHARACTER VARYING(250) NULL,
	equipment_name CHARACTER VARYING(255) NULL,
	rack_external_id CHARACTER VARYING(50) NULL,
	rack_name CHARACTER VARYING(255) NULL,
	workplace_external_id CHARACTER VARYING(50) NULL,
	workplace_name CHARACTER VARYING(255) NULL,
	room_external_id CHARACTER VARYING(50) NULL,
	room_name CHARACTER VARYING(255) NULL,
	location CHARACTER VARYING(500) NULL,
	building_external_id CHARACTER VARYING(50) NULL,
	building_name CHARACTER VARYING(255) NULL,
	agreement CHARACTER VARYING(255) NULL,
	user_name CHARACTER VARYING(100) NULL,
	founding CHARACTER VARYING(255) NULL,
	cost decimal NULL,
	warranty timestamp NULL,
	date_received timestamp NULL,
	user_field1 CHARACTER VARYING(255) NULL,
	user_field2 CHARACTER VARYING(255) NULL,
	user_field3 CHARACTER VARYING(255) NULL,
	user_field4 CHARACTER VARYING(255) NULL,
	user_field5 CHARACTER VARYING(255) NULL,
	ip_address CHARACTER VARYING(15) NULL,
	mac_address CHARACTER VARYING(23) NULL,
	domain CHARACTER VARYING(100) NULL,
	domain_login CHARACTER VARYING(100) NULL,
	login CHARACTER VARYING(100) NULL,
	os CHARACTER VARYING(255) NULL,
	ip_mask CHARACTER VARYING(15) NULL,
	CONSTRAINT pk_it_asset_undisposed PRIMARY KEY (id),
	CONSTRAINT fk_it_asset_undisposed_it_asset_import_setting FOREIGN KEY (it_asset_import_setting_id) REFERENCES im.it_asset_import_setting(id) ON DELETE CASCADE
)