// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;
using InfraManager.DAL.Asset;

namespace InfraManager.DAL.Microsoft.SqlServer.Configurations
{
    public partial class ElpsettingConfiguration : IEntityTypeConfiguration<ElpSetting>
    {
        public void Configure(EntityTypeBuilder<ElpSetting> entity)
        {
            entity.ToTable("ELPSetting", "dbo");

            entity.Property(e => e.Id)
                .HasColumnName("ID");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(500);

            entity.Property(e => e.Note).HasMaxLength(1000);

            entity.Property(e => e.VendorId).HasColumnName("VendorID");

            entity.HasOne(d => d.Vendor)
                .WithMany(p => p.Elpsetting)
                .HasPrincipalKey(p => p.ImObjID)
                .HasForeignKey(d => d.VendorId)
                .HasConstraintName("FK__ELPSetting_VendorID");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ElpSetting> entity);
    }
}
