// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;
using InfraManager.DAL.Events;

namespace InfraManager.DAL.Microsoft.SqlServer.Configurations
{
    public partial class EventSubjectParamConfiguration : IEntityTypeConfiguration<EventSubjectParam>
    {
        public void Configure(EntityTypeBuilder<EventSubjectParam> entity)
        {
            entity.ToTable("EventSubjectParam", "dbo");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");

            entity.Property(e => e.ParamName)
                .HasColumnName("ParamName")
                .IsRequired()
                .HasMaxLength(255);

            entity.Property(e => e.ParamNewValue)
                .HasColumnName("ParamNewValue")
                .IsRequired()
                .HasMaxLength(255);

            entity.Property(e => e.ParamOldValue)
                .HasColumnName("ParamOldValue")
                .HasMaxLength(255);
        }
    }
}
