// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using InfraManager.DAL.Asset;
using InfraManager.DAL.EntityConfigurations;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;
using IM.Core.DAL.Microsoft.SqlServer;

namespace InfraManager.DAL.Microsoft.SqlServer.Configurations;

internal sealed class MaterialConsumptionRateConfiguration : MaterialConsumptionRateConfigurationBase
{
    protected override string PrimaryKeyName => "PK_MaterialConsumptionRate";

    protected override string MaterialModelForeignKeyName => "FK_MaterialConsumptionRate_MaterialModel";

    protected override string IndexByMaterialModelID => "IX_MaterialConsumptionRate_MaterialModelID";

    protected override string IndexByDeviceCategoryID => "IX_MaterialConsumptionRate_DeviceModelID";

    protected override void ConfigureDataBase(EntityTypeBuilder<MaterialConsumptionRate> entity)
    {
        entity.ToTable("MaterialConsumptionRate", Options.Scheme);

        entity.Property(e => e.ID).HasColumnName("MCRID");
        entity.Property(e => e.DeviceModelID).HasColumnName("DeviceModelID");
        entity.Property(e => e.DeviceCategoryID).HasColumnName("DeviceCategoryID");
        entity.Property(e => e.MaterialModelID).HasColumnName("MaterialModelID");
        entity.Property(e => e.Amount).HasColumnName("Amount").HasColumnType("decimal");
        entity.Property(e => e.UseBWPrint).HasColumnName("UseBWPrint");
        entity.Property(e => e.UseColorPrint).HasColumnName("UseColorPrint");
        entity.Property(e => e.UsePhotoPrint).HasColumnName("UseFotoPrint");

        
    }
}
