// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using InfraManager.DAL.Asset;
using InfraManager.DAL.EntityConfigurations;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;

namespace InfraManager.DAL.Microsoft.SqlServer.Configurations
{
    public partial class PortTemplateConfiguration : PortTemplateConfigurationBase
    {
        protected override string PrimaryKeyName => "PK_PortTemplate";

        protected override string Schema => "dbo";
        
        protected override string TableName => "PortTemplate";

        protected override void AdditionalConfig(EntityTypeBuilder<PortTemplate> entity)
        {

            entity.Property(e => e.ObjectID).HasColumnName("ObjectID");

            entity.Property(e => e.ClassID).HasColumnName("ObjectClassID");

            entity.Property(e => e.PortNumber).HasColumnName("Number");
           
            entity.Property(e => e.JackTypeID).HasColumnName("JackTypeID");
            
            entity.Property(e => e.TechnologyID).HasColumnName("TechnologyTypeID");

            entity.HasIndex(x => x.ObjectID).HasDatabaseName("IX_PortTemplate_ObjectID");
            
            entity.HasOne(x => x.JackType)
                .WithMany()
                .HasForeignKey(x => x.JackTypeID)
                .HasConstraintName("FK_PortTemplate_JackType");

            entity.HasOne(x => x.TechnologyType)
                .WithMany()
                .HasForeignKey(x => x.TechnologyID)
                .HasConstraintName("FK_PortTemplate_TechnologyType");
            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PortTemplate> entity);
    }
}
