// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using InfraManager.DAL.Software;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;


namespace InfraManager.DAL.Microsoft.SqlServer.Configurations
{
    public partial class SoftwareInstallationDependancesConfiguration : IEntityTypeConfiguration<SoftwareInstallationDependances>
    {
        public void Configure(EntityTypeBuilder<SoftwareInstallationDependances> entity)
        {
            entity.ToTable("SoftwareInstallationDependances", "dbo");
            entity.HasKey(e => new { e.InstallationId, e.DependantInstallationId })
                .HasName("PK__SoftwareInstallationDependances");

            entity.Property(e => e.InstallationId).HasColumnName("InstallationID");

            entity.Property(e => e.DependantInstallationId).HasColumnName("DependantInstallationID");

            entity.HasOne(d => d.DependantInstallation)
                .WithMany(p => p.SoftwareInstallationDependancesDependantInstallation)
                .HasForeignKey(d => d.DependantInstallationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SoftwareInstallationDependance_dependant");

            entity.HasOne(d => d.Installation)
                .WithMany(p => p.SoftwareInstallationDependancesInstallation)
                .HasForeignKey(d => d.InstallationId)
                .HasConstraintName("FK_SoftwareInstallationDependance_primary");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SoftwareInstallationDependances> entity);
    }
}
