// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using InfraManager.DAL.Software;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;


namespace InfraManager.DAL.Microsoft.SqlServer.Configurations
{
    public partial class SoftwareLicenceSchemeConfiguration : IEntityTypeConfiguration<SoftwareLicenceScheme>
    {
        public void Configure(EntityTypeBuilder<SoftwareLicenceScheme> entity)
        {
            entity.ToTable("SoftwareLicenceScheme", "dbo");

            entity.HasKey(e => e.ID)
                .HasName("PK__SoftwareLicenceScheme")
                .IsClustered(false);

            entity.Property(e => e.ID)
                .ValueGeneratedNever()
                .HasColumnName("ID");

            entity.Property(e => e.AdditionalRights).HasMaxLength(4000);

            entity.Property(e => e.CompatibilityTypeID).HasColumnName("CompatibilityTypeID");

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.Description).HasMaxLength(4000);

            entity.Property(e => e.IncreaseForVm).HasColumnName("IncreaseForVM");

            entity.Property(e => e.InstallationLimitPerVm).HasColumnName("InstallationLimitPerVM");

            entity.Property(e => e.IsAllowInstallOnVm).HasColumnName("IsAllowInstallOnVM");

            entity.Property(e => e.LicenseCountPerObject).HasMaxLength(4000);

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(250);

            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SoftwareLicenceScheme> entity);
    }
}
