// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using InfraManager.DAL.Software;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;


namespace InfraManager.DAL.Microsoft.SqlServer.Configurations
{
    public partial class SoftwareModelUsingTypeConfiguration : IEntityTypeConfiguration<SoftwareModelUsingType>
    {
        public void Configure(EntityTypeBuilder<SoftwareModelUsingType> entity)
        {
            entity.ToTable("SoftwareModelUsingType", "dbo");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(250);

            entity.Property(e => e.Note)
                .IsRequired()
                .HasMaxLength(500);

            entity.Property(e => e.RowVersion)
                .IsRequired()
                .IsRowVersion()
                .IsConcurrencyToken();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SoftwareModelUsingType> entity);
    }
}
