// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using InfraManager.DAL.Software;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;


namespace InfraManager.DAL.Microsoft.SqlServer.Configurations
{
    public partial class SoftwareLicenceSchemeProcessorCoeffConfiguration : IEntityTypeConfiguration<SoftwareLicenceSchemeProcessorCoeff>
    {
        public void Configure(EntityTypeBuilder<SoftwareLicenceSchemeProcessorCoeff> entity)
        {
            entity.ToTable("SoftwareLicenceSchemeProcessorCoeff", "dbo");

            entity.HasKey(e => new { e.LicenceSchemeId, e.ProcessorTypeId })
                .HasName("PK__SoftwareLicenceSchemeProcessorCoeff");

            entity.Property(e => e.LicenceSchemeId).HasColumnName("LicenceSchemeID");

            entity.Property(e => e.ProcessorTypeId).HasColumnName("ProcessorTypeID");

            entity.HasOne(d => d.SoftwareLicenceScheme)
                .WithMany(p => p.SoftwareLicenceSchemeCoefficients)
                .HasForeignKey(d => d.LicenceSchemeId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_SoftwareLicenceSchemeCoefficients_SoftwareLicenceScheme");
            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SoftwareLicenceSchemeProcessorCoeff> entity);
    }
}
