// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using InfraManager.DAL.Software;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;


namespace InfraManager.DAL.Microsoft.SqlServer.Configurations
{
    public partial class UndisposedDeviceConfiguration : IEntityTypeConfiguration<UndisposedDevice>
    {
        public void Configure(EntityTypeBuilder<UndisposedDevice> entity)
        {
            entity.ToTable("UndisposedDevice", "dbo");
            entity.HasKey(e => e.DeviceId)
                .HasName("PK__UndisposedDevice");

            entity.HasIndex(e => e.DeviceId, "IX_UndisposedDevice_DeviceID");

            entity.HasIndex(e => e.IMObjID, "IX_UndisposedDevice_IMObjID");

            entity.Property(e => e.DeviceId)
                .ValueGeneratedNever()
                .HasColumnName("DeviceID");

            entity.Property(e => e.Agreement)
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.Property(e => e.BiosName).HasMaxLength(255);

            entity.Property(e => e.BiosVersion).HasMaxLength(255);

            entity.Property(e => e.BuildingName).HasMaxLength(255);

            entity.Property(e => e.ClassId).HasColumnName("ClassID");

            entity.Property(e => e.Code).HasMaxLength(50);

            entity.Property(e => e.ComputerName).HasMaxLength(255);

            entity.Property(e => e.Cost).HasColumnType("decimal(10, 2)");

            entity.Property(e => e.CsFormFactor).HasMaxLength(255);

            entity.Property(e => e.CsModel).HasMaxLength(255);

            entity.Property(e => e.CsSize).HasMaxLength(255);

            entity.Property(e => e.CsVendorId).HasColumnName("CsVendorID");

            entity.Property(e => e.DateInquiry).HasColumnType("datetime");

            entity.Property(e => e.DateReceived).HasColumnType("datetime");

            entity.Property(e => e.DefaultPrinter).HasMaxLength(255);

            entity.Property(e => e.Description)
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.Property(e => e.ExternalId)
                .HasMaxLength(250)
                .HasColumnName("ExternalID");

            entity.Property(e => e.Founding)
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.Property(e => e.IMObjID).HasColumnName("IMObjID");

            entity.Property(e => e.InvNumber).HasMaxLength(50);

            entity.Property(e => e.Ipaddress)
                .HasMaxLength(255)
                .HasColumnName("IPAddress");

            entity.Property(e => e.LocationString).HasMaxLength(2000);

            entity.Property(e => e.LogonDomain)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.Macaddress)
                .HasMaxLength(255)
                .HasColumnName("MACAddress");

            entity.Property(e => e.ManufacturerName)
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.Property(e => e.ModelExternalId)
                .HasMaxLength(250)
                .HasColumnName("ModelExternalID");

            entity.Property(e => e.ModelName)
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.Property(e => e.Note).HasMaxLength(255);

            entity.Property(e => e.OwningOrganization)
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.Property(e => e.ProductCatalogTemplateId).HasColumnName("ProductCatalogTemplateID");

            entity.Property(e => e.ReportId).HasColumnName("ReportID");

            entity.Property(e => e.ResponsibleUser)
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.Property(e => e.RoomName).HasMaxLength(255);

            entity.Property(e => e.SerlNumber).HasMaxLength(50);

            entity.Property(e => e.SmbiosassetTag)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("SMBIOSAssetTag");

            entity.Property(e => e.SourceName).HasMaxLength(500);

            entity.Property(e => e.SubNetMask).HasMaxLength(255);

            entity.Property(e => e.SupplierExternalId)
                .HasMaxLength(250)
                .HasColumnName("SupplierExternalID");

            entity.Property(e => e.SupplierName)
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.Property(e => e.TypeName).HasMaxLength(250);

            entity.Property(e => e.UserField1).HasMaxLength(255);

            entity.Property(e => e.UserField2).HasMaxLength(255);

            entity.Property(e => e.UserField3).HasMaxLength(255);

            entity.Property(e => e.UserField4).HasMaxLength(255);

            entity.Property(e => e.UserField5).HasMaxLength(255);

            entity.Property(e => e.UserName)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.UtilizerName)
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.Property(e => e.Warranty).HasColumnType("datetime");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UndisposedDevice> entity);
    }
}
