// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using InfraManager.DAL.Software;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;

namespace InfraManager.DAL.Microsoft.SqlServer.Configurations
{
    public partial class WebapiUsersConfiguration : IEntityTypeConfiguration<WebApiUsers>
    {
        public void Configure(EntityTypeBuilder<WebApiUsers> entity)
        {
            entity.HasKey(nameof(WebApiUsers.ImobjId));

            entity.ToView("webapi_Users", "dbo");

            entity.Property(e => e.Comments).HasMaxLength(100);

            entity.Property(e => e.DivisionId).HasColumnName("DivisionID");

            entity.Property(e => e.Email).HasMaxLength(100);

            entity.Property(e => e.ExternalId)
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnName("ExternalID");

            entity.Property(e => e.Fax).HasMaxLength(100);

            entity.Property(e => e.ImobjId).HasColumnName("IMObjID");

            entity.Property(e => e.LastName).HasMaxLength(100);

            entity.Property(e => e.Login).HasMaxLength(100);

            entity.Property(e => e.Name).HasMaxLength(100);

            entity.Property(e => e.Pager).HasMaxLength(100);

            entity.Property(e => e.Patronymic).HasMaxLength(100);

            entity.Property(e => e.Phone).HasMaxLength(100);

            entity.Property(e => e.PositionId).HasColumnName("PositionID");

            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.Property(e => e.WorkplaceId).HasColumnName("WorkplaceID");

            entity.Property(e => e.Removed).HasColumnName("Removed");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<WebApiUsers> entity);
    }
}
