if NOT EXISTS (SELECT 1
					FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS C
					WHERE C.TABLE_NAME = 'Setting'
						AND C.CONSTRAINT_SCHEMA = 'dbo' 
						AND C.CONSTRAINT_NAME = 'PK_Setting')
BEGIN 
	ALTER TABLE Setting
		ADD CONSTRAINT PK_Setting PRIMARY KEY CLUSTERED (id);
END 