if NOT EXISTS (SELECT 1
					FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS C
					WHERE C.TABLE_NAME = 'CallAdditionalField'
						AND C.CONSTRAINT_SCHEMA = 'dbo' 
						AND C.CONSTRAINT_NAME = 'PK_CallAdditionalField')
BEGIN 
	ALTER TABLE CallAdditionalField
		ADD CONSTRAINT PK_CallAdditionalField PRIMARY KEY CLUSTERED (id);
END 