if 'ITAssetUndisposed' not in (select [TABLE_NAME] from[INFORMATION_SCHEMA].[TABLES] where[TABLE_SCHEMA] = 'dbo')
    create table [dbo].[ITAssetUndisposed] (
		[ID] uniqueidentifier not null default(newid()),
		[ReasonCode] tinyint not null,
		[ITAssetImportSettingID] uniqueidentifier not null,
		[DetectionTime] datetime not null,
		[Name] nvarchar(255) null,
		[InvNumber] nvarchar(50) null,
		[SerialNumber] nvarchar(255) null,
		[Code] nvarchar(50) null,
		[ExternalID] nvarchar(250) null,
		[AssetTag] nvarchar(50) null,
		[Note] nvarchar(1000) null,
		[Description] nvarchar(250) null,
		[TypeExternalID] nvarchar(50) null,
		[TypeName] nvarchar(500) null,
		[ModelExternalID] nvarchar(250) null,
		[ModelName] nvarchar(255) null,
		[VendorExternalID] nvarchar(250) null,
		[VendorName] nvarchar(255) null,
		[SupplierExternalID] nvarchar(250) null,
		[SupplierName] nvarchar(255) null,
		[OwnerExternalID] nvarchar(500) null,
		[OwnerName] nvarchar(255) null,
		[UtilizerExternalID] nvarchar(500) null,
		[UtilizerName] nvarchar(255) null,
		[EquipmentExternalID] nvarchar(250) null,
		[EquipmentName] nvarchar(255) null,
		[RackExternalID] nvarchar(50) null,
		[RackName] nvarchar(255) null,
		[WorkplaceExternalID] nvarchar(50) null,
		[WorkplaceName] nvarchar(255) null,
		[RoomExternalID] nvarchar(50) null,
		[RoomName] nvarchar(255) null,
		[Location] nvarchar(500) null,
		[BuildingExternalID] nvarchar(50) null,
		[BuildingName] nvarchar(255) null,
		[Agreement] nvarchar(255) null,
		[UserName] nvarchar(100) null,
		[Founding] nvarchar(255) null,
		[Cost] decimal null,
		[Warranty] datetime null,
		[DateReceived] datetime null,
		[UserField1] nvarchar(255) null,
		[UserField2] nvarchar(255) null,
		[UserField3] nvarchar(255) null,
		[UserField4] nvarchar(255) null,
		[UserField5] nvarchar(255) null,
		[IpAddress] nvarchar(15) null,
		[MacAddress] nvarchar(23) null,
		[Domain] nvarchar(100) null,
		[DomainLogin] nvarchar(100) null,
		[Login] nvarchar(100) null,
		[OS] nvarchar(255) null,
		[IpMask] nvarchar(15) null,
		constraint PK_ITAssetUndisposed primary key clustered ([ID]),
		constraint FK_ITAssetUndisposed_ITAssetImportSetting foreign key ([ITAssetImportSettingID]) references [dbo].[ITAssetImportSetting]([ID]) ON DELETE CASCADE)
go