DECLARE @SUPPORTLINECOUNTLEN INT;
DECLARE @MONITORINGMESSAGESETTINGLEN INT;
DECLARE @LEN124 INT;

SET @SUPPORTLINECOUNTLEN = (SELECT CONVERT(BINARY(1), VALUE) FROM [Setting] WHERE Id = 70)
SET @MONITORINGMESSAGESETTINGLEN = (SELECT CONVERT(INT, CONVERT(VARBINARY, VALUE)) FROM [Setting] WHERE Id = 123)
SET @LEN124 = (SELECT CONVERT(int, CONVERT(VARBINARY, VALUE)) FROM [Setting] WHERE Id = 124)

IF @SUPPORTLINECOUNTLEN != 1
UPDATE [Setting] SET Value = CONVERT(BINARY(1), '0x1') WHERE Id = 70

IF @MONITORINGMESSAGESETTINGLEN IS NULL
INSERT INTO [Setting](ID, Value, RowVersion) VALUES (123, CONVERT(IMAGE, CONVERT(VARBINARY, 4)), NULL)

IF @LEN124 IS NULL
INSERT INTO [Setting](ID, Value, RowVersion) VALUES (124, CONVERT(IMAGE, CONVERT(VARBINARY, 4)), NULL)
