IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
   WHERE [TABLE_SCHEMA] = 'dbo' AND [TABLE_NAME] = 'Asset' AND [CONSTRAINT_TYPE] = 'PRIMARY KEY' AND [CONSTRAINT_NAME] = 'PK_Asset'))

	BEGIN

		ALTER TABLE [dbo].[Asset] ADD CONSTRAINT PK_Asset PRIMARY KEY ([ID]);

	END