using System.Linq;
using AutoMapper;
using InfraManager.BLL.AutoMapper;
using InfraManager.Core.Extensions;
using InfraManager.DAL.OrganizationStructure;
using InfraManager.DAL.ServiceDesk;
using InfraManager.DAL.ServiceDesk.ChangeRequests;
using InfraManager.DAL.ServiceDesk.MassIncidents;
using InfraManager.DAL.ServiceDesk.Negotiations;

namespace InfraManager.BLL.Notification.Templates
{
    public  class TemplateProfile : Profile
    {
        public TemplateProfile()
        {
            CreateMap<Negotiation, NegotiationTemplate>()
                .ForMember(dst => dst.ID, opt => opt.MapFrom(src => src.IMObjID))
                .ForMember(dst => dst.StatusString, opt => opt.MapFrom<LocalizedEnumResolver<Negotiation, NegotiationTemplate, NegotiationStatus>,NegotiationStatus>(src => src.Status))
                .ForMember(dst => dst.ModeString, opt => opt.MapFrom<LocalizedEnumResolver<Negotiation, NegotiationTemplate, NegotiationMode>, NegotiationMode>(src => src.Mode))
                ;

            CreateMap<Call, NegotiationTemplate>()
                .ForMember(dst => dst.CallQueueName, opt => opt.MapFrom(src => src.Queue == null ? null : src.Queue.Name))
                .ForMember(dst => dst.CallPriorityName, opt => opt.MapFrom(src => src.Priority == null ? null : src.Priority.Name))
                .ForMember(dst => dst.CallReceiptTypeString, opt => opt.MapFrom<LocalizedEnumResolver<Call, NegotiationTemplate, CallReceiptType>, CallReceiptType>(src => src.ReceiptType))
                .ForMember(dst => dst.CallRFSResultName, opt => opt.MapFrom(src => src.RequestForServiceResult == null ? null : src.RequestForServiceResult.Name))
                .ForMember(dst => dst.CallServiceItemFullName, opt => opt.MapFrom(src => src.CallService== null ? null : src.CallService.ServiceItem == null ? null : src.CallService.ServiceItem.Name))
                .ForMember(dst => dst.CallServiceAttendanceFullName, opt => opt.MapFrom(src => src.CallService == null ? null : src.CallService.ServiceAttendance == null ? null : src.CallService.ServiceAttendance.Name))
                .ForMember(dst => dst.CallAccomplisherBuildingName, opt => opt.MapFrom(src => src.Accomplisher== null ? null : src.Accomplisher.BuildingName))
                .ForMember(dst => dst.CallAccomplisherEmail, opt => opt.MapFrom(src => src.Accomplisher == null ? null : src.Accomplisher.Email))
                .ForMember(dst => dst.CallAccomplisherFax, opt => opt.MapFrom(src => src.Accomplisher == null ? null : src.Accomplisher.Fax))
                .ForMember(dst => dst.CallAccomplisherFirstName, opt => opt.MapFrom(src => src.Accomplisher == null ? null : src.Accomplisher.Name))
                .ForMember(dst => dst.CallAccomplisherFullName, opt => opt.MapFrom(src => src.Accomplisher == null ? null : src.Accomplisher.FullName))
                .ForMember(dst => dst.CallAccomplisherLastName, opt => opt.MapFrom(src => src.Accomplisher == null ? null : src.Accomplisher.Surname))
                .ForMember(dst => dst.CallAccomplisherLogin, opt => opt.MapFrom(src => src.Accomplisher == null ? null : src.Accomplisher.LoginName))
                .ForMember(dst => dst.CallAccomplisherNumber, opt => opt.MapFrom(src => src.Accomplisher == null ? null : src.Accomplisher.Number))
                .ForMember(dst => dst.CallAccomplisherOrganizationName, opt => opt.MapFrom(src => src.Accomplisher == null ? null : src.Accomplisher.OrganizationName))
                .ForMember(dst => dst.CallAccomplisherPager, opt => opt.MapFrom(src => src.Accomplisher == null ? null : src.Accomplisher.Pager))
                .ForMember(dst => dst.CallAccomplisherPatronymic, opt => opt.MapFrom(src => src.Accomplisher == null ? null : src.Accomplisher.Patronymic))
                .ForMember(dst => dst.CallAccomplisherPhone, opt => opt.MapFrom(src => src.Accomplisher == null ? null : src.Accomplisher.Phone))
                .ForMember(dst => dst.CallAccomplisherPositionName, opt => opt.MapFrom(src => src.Accomplisher == null ? null : src.Accomplisher.PositionName))
                .ForMember(dst => dst.CallAccomplisherRoomName, opt => opt.MapFrom(src => src.Accomplisher == null ? null : src.Accomplisher.RoomName))
                .ForMember(dst => dst.CallAccomplisherSubdivisionName, opt => opt.MapFrom(src => src.Accomplisher == null ? null : src.Accomplisher.SubdivisionName))
                .ForMember(dst => dst.CallAccomplisherWorkplaceName, opt => opt.MapFrom(src => src.Accomplisher == null ? null : src.Accomplisher.WorkplaceName))
                .ForMember(dst => dst.CallCallSummaryName, opt => opt.MapFrom(src => src.CallSummaryName))
                .ForMember(dst => dst.CallCallTypeFullName, opt => opt.MapFrom(src => src.CallType == null ? null : src.CallType.Name))
                .ForMember(dst => dst.CallClientBuildingName, opt => opt.MapFrom(src => src.Client == null ? null : src.Client.BuildingName))
                .ForMember(dst => dst.CallClientEmail, opt => opt.MapFrom(src => src.Client == null ? null : src.Client.Email))
                .ForMember(dst => dst.CallClientFax, opt => opt.MapFrom(src => src.Client == null ? null : src.Client.Fax))
                .ForMember(dst => dst.CallClientFirstName, opt => opt.MapFrom(src => src.Client == null ? null : src.Client.Name))
                .ForMember(dst => dst.CallClientFullName, opt => opt.MapFrom(src => src.Client == null ? null : src.Client.FullName))
                .ForMember(dst => dst.CallClientLastName, opt => opt.MapFrom(src => src.Client == null ? null : src.Client.Surname))
                .ForMember(dst => dst.CallClientLogin, opt => opt.MapFrom(src => src.Client == null ? null : src.Client.LoginName))
                .ForMember(dst => dst.CallClientNumber, opt => opt.MapFrom(src => src.Client == null ? null : src.Client.Number))
                .ForMember(dst => dst.CallClientOrganizationName, opt => opt.MapFrom(src => src.Client == null ? null : src.Client.OrganizationName))
                .ForMember(dst => dst.CallClientPager, opt => opt.MapFrom(src => src.Client == null ? null : src.Client.Pager))
                .ForMember(dst => dst.CallClientPatronymic, opt => opt.MapFrom(src => src.Client == null ? null : src.Client.Patronymic))
                .ForMember(dst => dst.CallClientPhone, opt => opt.MapFrom(src => src.Client == null ? null : src.Client.Phone))
                .ForMember(dst => dst.CallClientPositionName, opt => opt.MapFrom(src => src.Client == null ? null : src.Client.PositionName))
                .ForMember(dst => dst.CallClientRoomName, opt => opt.MapFrom(src => src.Client == null ? null : src.Client.RoomName))
                .ForMember(dst => dst.CallClientSubdivisionName, opt => opt.MapFrom(src => src.Client == null ? null : src.Client.SubdivisionName))
                .ForMember(dst => dst.CallClientWorkplaceName, opt => opt.MapFrom(src => src.Client == null ? null : src.Client.WorkplaceName))
                .ForMember(dst => dst.CallDateAccomplishedString, opt => opt.MapFrom(src => src.UtcDateAccomplished.ToStringOrEmpty()))
                .ForMember(dst => dst.CallDateClosedString, opt => opt.MapFrom(src => src.UtcDateClosed.ToStringOrEmpty()))
                .ForMember(dst => dst.CallDateModifiedString, opt => opt.MapFrom(src => src.UtcDateModified.ToStringOrEmpty()))
                .ForMember(dst => dst.CallDateOpenedString, opt => opt.MapFrom(src => src.UtcDateOpened.ToStringOrEmpty()))
                .ForMember(dst => dst.CallDatePromisedString, opt => opt.MapFrom(src => src.UtcDatePromised.ToStringOrEmpty()))
                .ForMember(dst => dst.CallDateRegisteredString, opt => opt.MapFrom(src => src.UtcDateRegistered.ToStringOrEmpty()))
                .ForMember(dst => dst.CallDescription, opt => opt.MapFrom(src => src.Description))
                .ForMember(dst => dst.CallEntityStateName, opt => opt.MapFrom(src => src.EntityStateName))
                .ForMember(dst => dst.CallExecutorBuildingName, opt => opt.MapFrom(src => src.Executor == null ? null : src.Executor.BuildingName))
                .ForMember(dst => dst.CallExecutorEmail, opt => opt.MapFrom(src => src.Executor == null ? null : src.Executor.Email))
                .ForMember(dst => dst.CallExecutorFax, opt => opt.MapFrom(src => src.Executor == null ? null : src.Executor.Fax))
                .ForMember(dst => dst.CallExecutorFirstName, opt => opt.MapFrom(src => src.Executor == null ? null : src.Executor.Name))
                .ForMember(dst => dst.CallExecutorFullName, opt => opt.MapFrom(src => src.Executor == null ? null : src.Executor.FullName))
                .ForMember(dst => dst.CallExecutorLastName, opt => opt.MapFrom(src => src.Executor == null ? null : src.Executor.Surname))
                .ForMember(dst => dst.CallExecutorLogin, opt => opt.MapFrom(src => src.Executor == null ? null : src.Executor.LoginName))
                .ForMember(dst => dst.CallExecutorNumber, opt => opt.MapFrom(src => src.Executor == null ? null : src.Executor.Number))
                .ForMember(dst => dst.CallExecutorOrganizationName, opt => opt.MapFrom(src => src.Executor == null ? null : src.Executor.OrganizationName))
                .ForMember(dst => dst.CallExecutorPager, opt => opt.MapFrom(src => src.Executor == null ? null : src.Executor.Pager))
                .ForMember(dst => dst.CallExecutorPatronymic, opt => opt.MapFrom(src => src.Executor == null ? null : src.Executor.Patronymic))
                .ForMember(dst => dst.CallExecutorPhone, opt => opt.MapFrom(src => src.Executor == null ? null : src.Executor.Phone))
                .ForMember(dst => dst.CallExecutorPositionName, opt => opt.MapFrom(src => src.Executor == null ? null : src.Executor.PositionName))
                .ForMember(dst => dst.CallExecutorRoomName, opt => opt.MapFrom(src => src.Executor == null ? null : src.Executor.RoomName))
                .ForMember(dst => dst.CallExecutorSubdivisionName, opt => opt.MapFrom(src => src.Executor == null ? null : src.Executor.SubdivisionName))
                .ForMember(dst => dst.CallExecutorWorkplaceName, opt => opt.MapFrom(src => src.Executor == null ? null : src.Executor.WorkplaceName))
                .ForMember(dst => dst.CallGradeString, opt => opt.MapFrom(src => src.Grade == null ? null : src.Grade.ToString()))
                .ForMember(dst => dst.CallIncidentResultName, opt => opt.MapFrom(src => src.IncidentResult == null ? null : src.IncidentResult.Name))
                .ForMember(dst => dst.CallInfluenceName, opt => opt.MapFrom(src => src.Influence == null ? null : src.Influence.Name))
                .ForMember(dst => dst.CallInitiatorBuildingName, opt => opt.MapFrom(src => src.Initiator == null ? null : src.Initiator.BuildingName))
                .ForMember(dst => dst.CallInitiatorEmail, opt => opt.MapFrom(src => src.Initiator == null ? null : src.Initiator.Email))
                .ForMember(dst => dst.CallInitiatorFax, opt => opt.MapFrom(src => src.Initiator == null ? null : src.Initiator.Fax))
                .ForMember(dst => dst.CallInitiatorFirstName, opt => opt.MapFrom(src => src.Initiator == null ? null : src.Initiator.Name))
                .ForMember(dst => dst.CallInitiatorFullName, opt => opt.MapFrom(src => src.Initiator == null ? null : src.Initiator.FullName))
                .ForMember(dst => dst.CallInitiatorLastName, opt => opt.MapFrom(src => src.Initiator == null ? null : src.Initiator.Surname))
                .ForMember(dst => dst.CallInitiatorLogin, opt => opt.MapFrom(src => src.Initiator == null ? null : src.Initiator.LoginName))
                .ForMember(dst => dst.CallInitiatorNumber, opt => opt.MapFrom(src => src.Initiator == null ? null : src.Initiator.Number))
                .ForMember(dst => dst.CallInitiatorOrganizationName, opt => opt.MapFrom(src => src.Initiator == null ? null : src.Initiator.OrganizationName))
                .ForMember(dst => dst.CallInitiatorPager, opt => opt.MapFrom(src => src.Initiator == null ? null : src.Initiator.Pager))
                .ForMember(dst => dst.CallInitiatorPatronymic, opt => opt.MapFrom(src => src.Initiator == null ? null : src.Initiator.Patronymic))
                .ForMember(dst => dst.CallInitiatorPhone, opt => opt.MapFrom(src => src.Initiator == null ? null : src.Initiator.Phone))
                .ForMember(dst => dst.CallInitiatorPositionName, opt => opt.MapFrom(src => src.Initiator == null ? null : src.Initiator.PositionName))
                .ForMember(dst => dst.CallInitiatorRoomName, opt => opt.MapFrom(src => src.Initiator == null ? null : src.Initiator.RoomName))
                .ForMember(dst => dst.CallInitiatorSubdivisionName, opt => opt.MapFrom(src => src.Initiator == null ? null : src.Initiator.SubdivisionName))
                .ForMember(dst => dst.CallInitiatorWorkplaceName, opt => opt.MapFrom(src => src.Initiator == null ? null : src.Initiator.WorkplaceName))
                .ForMember(dst => dst.CallNumberString, opt => opt.MapFrom(src => src.Number.ToString()))
                .ForMember(dst => dst.CallOwnerBuildingName, opt => opt.MapFrom(src => src.Owner == null ? null : src.Owner.BuildingName))
                .ForMember(dst => dst.CallOwnerEmail, opt => opt.MapFrom(src => src.Owner == null ? null : src.Owner.Email))
                .ForMember(dst => dst.CallOwnerFax, opt => opt.MapFrom(src => src.Owner == null ? null : src.Owner.Fax))
                .ForMember(dst => dst.CallOwnerFirstName, opt => opt.MapFrom(src => src.Owner == null ? null : src.Owner.Name))
                .ForMember(dst => dst.CallOwnerFullName, opt => opt.MapFrom(src => src.Owner == null ? null : src.Owner.FullName))
                .ForMember(dst => dst.CallOwnerLastName, opt => opt.MapFrom(src => src.Owner == null ? null : src.Owner.Surname))
                .ForMember(dst => dst.CallOwnerLogin, opt => opt.MapFrom(src => src.Owner == null ? null : src.Owner.LoginName))
                .ForMember(dst => dst.CallOwnerNumber, opt => opt.MapFrom(src => src.Owner == null ? null : src.Owner.Number))
                .ForMember(dst => dst.CallOwnerOrganizationName, opt => opt.MapFrom(src => src.Owner == null ? null : src.Owner.OrganizationName))
                .ForMember(dst => dst.CallOwnerPager, opt => opt.MapFrom(src => src.Owner == null ? null : src.Owner.Pager))
                .ForMember(dst => dst.CallOwnerPatronymic, opt => opt.MapFrom(src => src.Owner == null ? null : src.Owner.Patronymic))
                .ForMember(dst => dst.CallOwnerPhone, opt => opt.MapFrom(src => src.Owner == null ? null : src.Owner.Phone))
                .ForMember(dst => dst.CallOwnerPositionName, opt => opt.MapFrom(src => src.Owner == null ? null : src.Owner.PositionName))
                .ForMember(dst => dst.CallOwnerRoomName, opt => opt.MapFrom(src => src.Owner == null ? null : src.Owner.RoomName))
                .ForMember(dst => dst.CallOwnerSubdivisionName, opt => opt.MapFrom(src => src.Owner == null ? null : src.Owner.SubdivisionName))
                .ForMember(dst => dst.CallOwnerWorkplaceName, opt => opt.MapFrom(src => src.Owner == null ? null : src.Owner.WorkplaceName))
                .ForMember(dst => dst.CallServiceName, opt => opt.MapFrom(src => src.CallService == null ? null : src.CallService.ServiceName))
                .ForMember(dst => dst.CallSolution, opt => opt.MapFrom(src => src.Solution))
                .ForMember(dst => dst.CallUrgencyName, opt => opt.MapFrom(src => src.Urgency == null ? null : src.Urgency.Name))
                .ForMember(dst => dst.CallEscalationCountString, opt => opt.MapFrom(src => src.EscalationCount))
                .ForAllOtherMembers(o=>o.Ignore())
                ;

            CreateMap<Problem, NegotiationTemplate>()
                .ForMember(dst => dst.ProblemEntityStateName, opt => opt.MapFrom(src => src.EntityStateName))
                .ForMember(dst => dst.ProblemNumberString, opt => opt.MapFrom(src => src.Number.ToString()))
                .ForMember(dst => dst.ProblemDescription, opt => opt.MapFrom(src => src.Description))
                .ForMember(dst => dst.ProblemSolution, opt => opt.MapFrom(src => src.Solution))
                .ForMember(dst => dst.ProblemSummary, opt => opt.MapFrom(src => src.Summary))
                .ForMember(dst => dst.ProblemCause, opt => opt.MapFrom(src => src.Cause))
                .ForMember(dst => dst.ProblemFix, opt => opt.MapFrom(src => src.Fix))
                .ForMember(dst => dst.ProblemDateDetectedString, opt => opt.MapFrom(src => src.UtcDateDetected.ToStringOrEmpty()))
                .ForMember(dst => dst.ProblemDatePromisedString, opt => opt.MapFrom(src => src.UtcDatePromised.ToStringOrEmpty()))
                .ForMember(dst => dst.ProblemDateSolvedString, opt => opt.MapFrom(src => src.UtcDateSolved.ToStringOrEmpty()))
                .ForMember(dst => dst.ProblemDateClosedString, opt => opt.MapFrom(src => src.UtcDateClosed.ToStringOrEmpty()))
                .ForMember(dst => dst.ProblemDateModifiedString, opt => opt.MapFrom(src => src.UtcDateModified.ToStringOrEmpty()))
                .ForMember(dst => dst.ProblemProblemTypeFullName, opt => opt.MapFrom(src => src.Type != null ? src.Type.FullName : null))
                .ForMember(dst => dst.ProblemProblemCauseName, opt => opt.MapFrom(src => src.ProblemCause != null ? src.ProblemCause.Name : null))
                .ForMember(dst => dst.ProblemUrgencyName, opt => opt.MapFrom(src => src.Urgency != null ? src.Urgency.Name : null))
                .ForMember(dst => dst.ProblemInfluenceName, opt => opt.MapFrom(src => src.Influence != null ? src.Influence.Name : null))
                .ForMember(dst => dst.ProblemPriorityName, opt => opt.MapFrom(src => src.Priority != null ? src.Priority.Name : null))
                .ForMember(dst => dst.ProblemOwnerLastName, opt => opt.MapFrom(src => src.Owner != null ? src.Owner.Surname : null))
                .ForMember(dst => dst.ProblemOwnerFirstName, opt => opt.MapFrom(src => src.Owner != null ? src.Owner.Name : null))
                .ForMember(dst => dst.ProblemOwnerPatronymic, opt => opt.MapFrom(src => src.Owner != null ? src.Owner.Patronymic : null))
                .ForMember(dst => dst.ProblemOwnerFullName, opt => opt.MapFrom(src => src.Owner != null ? src.Owner.FullName : null))
                .ForMember(dst => dst.ProblemOwnerLogin, opt=> opt.MapFrom(src => src.Owner != null ? src.Owner.LoginName : null))
                .ForMember(dst => dst.ProblemOwnerPhone, opt => opt.MapFrom(src => src.Owner != null ? src.Owner.Phone : null))
                .ForMember(dst => dst.ProblemOwnerNumber, opt => opt.MapFrom(src => src.Owner != null ? src.Owner.Number : null))
                .ForMember(dst => dst.ProblemOwnerEmail, opt => opt.MapFrom(src => src.Owner != null ? src.Owner.Email : null))
                .ForMember(dst => dst.ProblemOwnerFax, opt => opt.MapFrom(src => src.Owner != null ? src.Owner.Fax : null))
                .ForMember(dst => dst.ProblemOwnerPager, opt => opt.MapFrom(src => src.Owner != null ? src.Owner.Pager : null))
                .ForMember(dst => dst.ProblemOwnerPositionName, opt => opt.MapFrom(src => src.Owner != null ? src.Owner.PositionName : null))
                .ForMember(dst => dst.ProblemOwnerBuildingName, opt => opt.MapFrom(src => src.Owner != null ? src.Owner.BuildingName : null))
                .ForMember(dst => dst.ProblemOwnerRoomName, opt => opt.MapFrom(src => src.Owner != null ? src.Owner.RoomName : null))
                .ForMember(dst => dst.ProblemOwnerWorkplaceName, opt => opt.MapFrom(src => src.Owner != null ? src.Owner.WorkplaceName : null))
                .ForMember(dst => dst.ProblemOwnerOrganizationName, opt => opt.MapFrom(src => src.Owner != null ? src.Owner.OrganizationName : null))
                .ForMember(dst => dst.ProblemOwnerSubdivisionName, opt => opt.MapFrom(src => src.Owner != null ? src.Owner.SubdivisionName : null))
                .ForAllOtherMembers(o => o.Ignore())
                ;
            
            CreateMap<ChangeRequest, NegotiationTemplate>()
                .ForMember(dst => dst.RFCEntityStateName, opt => opt.MapFrom(src => src.EntityStateName))
                .ForMember(dst => dst.RFCNumberString, opt => opt.MapFrom(src => src.Number.ToString()))
                .ForMember(dst => dst.RFCDescription, opt => opt.MapFrom(src => src.Description))
                .ForMember(dst => dst.RFCSummary, opt => opt.MapFrom(src => src.Summary))
                .ForMember(dst => dst.RFCDateDetectedString, opt => opt.MapFrom(src => src.UtcDateDetected.ToStringOrEmpty()))
                .ForMember(dst => dst.RFCDatePromisedString, opt => opt.MapFrom(src => src.UtcDatePromised.ToStringOrEmpty()))
                .ForMember(dst => dst.RFCDateStartedString,  opt => opt.MapFrom(src => src.UtcDateStarted.ToStringOrEmpty()))
                .ForMember(dst => dst.RFCDateSolvedString, opt => opt.MapFrom(src => src.UtcDateSolved.ToStringOrEmpty()))
                .ForMember(dst => dst.RFCDateClosedString, opt => opt.MapFrom(src => src.UtcDateClosed.ToStringOrEmpty()))
                .ForMember(dst => dst.RFCDateModifiedString, opt => opt.MapFrom(src => src.UtcDateModified.ToStringOrEmpty()))
                .ForMember(dst => dst.RFCTypeFullName, opt => opt.MapFrom(src => src.Type != null ? src.Type.Name : null))
                .ForMember(dst => dst.RFCCategoryFullName, opt => opt.MapFrom(src => src.Category != null ? src.Category.Name : null))
                .ForMember(dst => dst.RFCUrgencyName, opt => opt.MapFrom(src => src.Urgency != null ? src.Urgency.Name : null))
                .ForMember(dst => dst.RFCFundingAmount, opt => opt.MapFrom(src => src.FundingAmount.ToStringOrEmpty()))
                .ForMember(dst => dst.RFCInfluenceName, opt => opt.MapFrom(src => src.Influence != null ? src.Influence.Name : null))
                .ForMember(dst => dst.RFCPriorityName, opt => opt.MapFrom(src => src.Priority != null ? src.Priority.Name : null))
                .ForMember(dst => dst.RFCServiceName, opt => opt.MapFrom(src => src.ServiceName))
                .ForMember(dst => dst.RFCOwnerLastName, opt => opt.MapFrom(src => src.Owner != null ? src.Owner.Surname : null))
                .ForMember(dst => dst.RFCOwnerFirstName, opt => opt.MapFrom(src => src.Owner != null ? src.Owner.Name : null))
                .ForMember(dst => dst.RFCOwnerPatronymic, opt => opt.MapFrom(src => src.Owner != null ? src.Owner.Patronymic : null))
                .ForMember(dst => dst.RFCOwnerFullName, opt => opt.MapFrom(src => src.Owner != null ? src.Owner.FullName : null))
                .ForMember(dst => dst.RFCOwnerLogin, opt => opt.MapFrom(src => src.Owner != null ? src.Owner.LoginName : null))
                .ForMember(dst => dst.RFCOwnerPhone, opt => opt.MapFrom(src => src.Owner != null ? src.Owner.Phone : null))
                .ForMember(dst => dst.RFCOwnerNumber, opt => opt.MapFrom(src => src.Owner != null ? src.Owner.Number : null))
                .ForMember(dst => dst.RFCOwnerEmail, opt => opt.MapFrom(src => src.Owner != null ? src.Owner.Email : null))
                .ForMember(dst => dst.RFCOwnerFax, opt => opt.MapFrom(src => src.Owner != null ? src.Owner.Fax : null))
                .ForMember(dst => dst.RFCOwnerPager, opt => opt.MapFrom(src => src.Owner != null ? src.Owner.Pager : null))
                .ForMember(dst => dst.RFCOwnerPositionName, opt => opt.MapFrom(src => src.Owner != null ? src.Owner.PositionName : null))
                .ForMember(dst => dst.RFCOwnerBuildingName, opt => opt.MapFrom(src => src.Owner != null ? src.Owner.BuildingName : null))
                .ForMember(dst => dst.RFCOwnerRoomName, opt => opt.MapFrom(src => src.Owner != null ? src.Owner.RoomName : null))
                .ForMember(dst => dst.RFCOwnerWorkplaceName, opt => opt.MapFrom(src => src.Owner != null ? src.Owner.WorkplaceName : null))
                .ForMember(dst => dst.RFCOwnerOrganizationName, opt => opt.MapFrom(src => src.Owner != null ? src.Owner.OrganizationName : null))
                .ForMember(dst => dst.RFCOwnerSubdivisionName, opt => opt.MapFrom(src => src.Owner != null ? src.Owner.SubdivisionName : null))
                .ForMember(dst => dst.RFCTarget, opt => opt.MapFrom(src => src.Target))
                .ForMember(dst => dst.RFCManHoursString, opt => opt.MapFrom(src => src.ManhoursInMinutes.ToStringOrEmpty()))
                .ForMember(dst => dst.RFCManhoursNormString, opt => opt.MapFrom(src => src.ManhoursNormInMinutes))
                .ForMember(dst => dst.RFCInitiatorLastName, opt => opt.MapFrom(src => src.Initiator != null ? src.Initiator.Surname : null))
                .ForMember(dst => dst.RFCInitiatorFirstName, opt => opt.MapFrom(src => src.Initiator != null ? src.Initiator.Name : null))
                .ForMember(dst => dst.RFCInitiatorPatronymic, opt => opt.MapFrom(src => src.Initiator != null ? src.Initiator.Patronymic : null))
                .ForMember(dst => dst.RFCInitiatorFullName, opt => opt.MapFrom(src => src.Initiator != null ? src.Initiator.FullName : null))
                .ForMember(dst => dst.RFCInitiatorLogin, opt => opt.MapFrom(src => src.Initiator != null ? src.Initiator.LoginName : null))
                .ForMember(dst => dst.RFCInitiatorPhone, opt => opt.MapFrom(src => src.Initiator != null ? src.Initiator.Phone : null))
                .ForMember(dst => dst.RFCInitiatorNumber, opt => opt.MapFrom(src => src.Initiator != null ? src.Initiator.Number : null))
                .ForMember(dst => dst.RFCInitiatorEmail, opt => opt.MapFrom(src => src.Initiator != null ? src.Initiator.Email : null))
                .ForMember(dst => dst.RFCInitiatorFax, opt => opt.MapFrom(src => src.Initiator != null ? src.Initiator.Fax : null))
                .ForMember(dst => dst.RFCInitiatorPager, opt => opt.MapFrom(src => src.Initiator != null ? src.Initiator.Pager : null))
                .ForMember(dst => dst.RFCInitiatorPositionName, opt => opt.MapFrom(src => src.Initiator != null ? src.Initiator.PositionName : null))
                .ForMember(dst => dst.RFCInitiatorBuildingName, opt => opt.MapFrom(src => src.Initiator != null ? src.Initiator.BuildingName : null))
                .ForMember(dst => dst.RFCInitiatorRoomName, opt => opt.MapFrom(src => src.Initiator != null ? src.Initiator.RoomName : null))
                .ForMember(dst => dst.RFCInitiatorWorkplaceName, opt => opt.MapFrom(src => src.Initiator != null ? src.Initiator.WorkplaceName : null))
                .ForMember(dst => dst.RFCInitiatorOrganizationName, opt => opt.MapFrom(src => src.Initiator != null ? src.Initiator.OrganizationName : null))
                .ForMember(dst => dst.RFCInitiatorSubdivisionName, opt => opt.MapFrom(src => src.Initiator != null ? src.Initiator.SubdivisionName : null))
                .ForAllOtherMembers(o => o.Ignore());

            CreateMap<WorkOrder, NegotiationTemplate>()
                .ForMember(dst => dst.WorkOrderEntityStateName, opt => opt.MapFrom(src => src.EntityStateName))
                .ForMember(dst => dst.WorkOrderNumberString, opt => opt.MapFrom(src => src.Number.ToString()))
                .ForMember(dst => dst.WorkOrderName, opt => opt.MapFrom(src => src.Name))
                .ForMember(dst => dst.WorkOrderDescription, opt => opt.MapFrom(src => src.Description))
                .ForMember(dst => dst.WorkOrderManHoursString, opt => opt.MapFrom(src => src.ManhoursInMinutes.ToStringOrEmpty()))
                .ForMember(dst => dst.WorkOrderManhoursNormString, opt => opt.MapFrom(src => src.ManhoursNormInMinutes.ToStringOrEmpty()))
                .ForMember(dst => dst.WorkOrderWorkOrderReferenceString, opt => opt.MapFrom(src => src.WorkOrderReference != null ? src.WorkOrderReference.ReferenceName : null))
                .ForMember(dst => dst.WorkOrderDateCreatedString, opt => opt.MapFrom(src => src.UtcDateCreated.ToStringOrEmpty()))
                .ForMember(dst => dst.WorkOrderDateModifiedString, opt => opt.MapFrom(src => src.UtcDateModified.ToStringOrEmpty()))
                .ForMember(dst => dst.WorkOrderDateAssignedString, opt => opt.MapFrom(src => src.UtcDateAssigned.ToStringOrEmpty()))
                .ForMember(dst => dst.WorkOrderDateAcceptedString, opt => opt.MapFrom(src => src.UtcDateAccepted.ToStringOrEmpty()))
                .ForMember(dst => dst.WorkOrderDatePromisedString, opt => opt.MapFrom(src => src.UtcDatePromised.ToStringOrEmpty()))
                .ForMember(dst => dst.WorkOrderDateStartedString, opt => opt.MapFrom(src => src.UtcDateStarted.ToStringOrEmpty()))
                .ForMember(dst => dst.WorkOrderDateAccomplishedString, opt => opt.MapFrom(src => src.UtcDateAccomplished.ToStringOrEmpty()))
                .ForMember(dst => dst.WorkOrderWorkOrderTypeName, opt => opt.MapFrom(src => src.Type != null ? src.Type.Name : null))
                .ForMember(dst => dst.WorkOrderWorkOrderPriorityName, opt => opt.MapFrom(src => src.Priority != null ? src.Priority.Name : null))
                .ForMember(dst => dst.WorkOrderInitiatorLastName, opt => opt.MapFrom(src => src.Initiator != null ? src.Initiator.Surname : null))
                .ForMember(dst => dst.WorkOrderInitiatorFirstName, opt => opt.MapFrom(src => src.Initiator != null ? src.Initiator.Name : null))
                .ForMember(dst => dst.WorkOrderInitiatorPatronymic, opt => opt.MapFrom(src => src.Initiator != null ? src.Initiator.Patronymic : null))
                .ForMember(dst => dst.WorkOrderInitiatorFullName, opt => opt.MapFrom(src => src.Initiator != null ? src.Initiator.FullName : null))
                .ForMember(dst => dst.WorkOrderInitiatorLogin, opt => opt.MapFrom(src => src.Initiator != null ? src.Initiator.LoginName : null))
                .ForMember(dst => dst.WorkOrderInitiatorPhone, opt => opt.MapFrom(src => src.Initiator != null ? src.Initiator.Phone : null))
                .ForMember(dst => dst.WorkOrderInitiatorNumber, opt => opt.MapFrom(src => src.Initiator != null ? src.Initiator.Number : null))
                .ForMember(dst => dst.WorkOrderInitiatorEmail, opt => opt.MapFrom(src => src.Initiator != null ? src.Initiator.Email : null))
                .ForMember(dst => dst.WorkOrderInitiatorFax, opt => opt.MapFrom(src => src.Initiator != null ? src.Initiator.Fax : null))
                .ForMember(dst => dst.WorkOrderInitiatorPager, opt => opt.MapFrom(src => src.Initiator != null ? src.Initiator.Pager : null))
                .ForMember(dst => dst.WorkOrderInitiatorPositionName, opt => opt.MapFrom(src => src.Initiator != null ? src.Initiator.PositionName : null))
                .ForMember(dst => dst.WorkOrderInitiatorBuildingName, opt => opt.MapFrom(src => src.Initiator != null ? src.Initiator.BuildingName : null))
                .ForMember(dst => dst.WorkOrderInitiatorRoomName, opt => opt.MapFrom(src => src.Initiator != null ? src.Initiator.RoomName : null))
                .ForMember(dst => dst.WorkOrderInitiatorWorkplaceName, opt => opt.MapFrom(src => src.Initiator != null ? src.Initiator.WorkplaceName : null))
                .ForMember(dst => dst.WorkOrderInitiatorOrganizationName, opt => opt.MapFrom(src => src.Initiator != null ? src.Initiator.OrganizationName : null))
                .ForMember(dst => dst.WorkOrderInitiatorSubdivisionName, opt => opt.MapFrom(src => src.Initiator != null ? src.Initiator.SubdivisionName : null))
                .ForMember(dst => dst.WorkOrderAssignorLastName, opt => opt.MapFrom(src => src.Assignee != null ? src.Assignee.Surname : null))
                .ForMember(dst => dst.WorkOrderAssignorFirstName, opt => opt.MapFrom(src => src.Assignee != null ? src.Assignee.Name : null))
                .ForMember(dst => dst.WorkOrderAssignorPatronymic, opt => opt.MapFrom(src => src.Assignee != null ? src.Assignee.Patronymic : null))
                .ForMember(dst => dst.WorkOrderAssignorFullName, opt => opt.MapFrom(src => src.Assignee != null ? src.Assignee.FullName : null))
                .ForMember(dst => dst.WorkOrderAssignorLogin, opt => opt.MapFrom(src => src.Assignee != null ? src.Assignee.LoginName : null))
                .ForMember(dst => dst.WorkOrderAssignorPhone, opt => opt.MapFrom(src => src.Assignee != null ? src.Assignee.Phone : null))
                .ForMember(dst => dst.WorkOrderAssignorNumber, opt => opt.MapFrom(src => src.Assignee != null ? src.Assignee.Number : null))
                .ForMember(dst => dst.WorkOrderAssignorEmail, opt => opt.MapFrom(src => src.Assignee != null ? src.Assignee.Email : null))
                .ForMember(dst => dst.WorkOrderAssignorFax, opt => opt.MapFrom(src => src.Assignee != null ? src.Assignee.Fax : null))
                .ForMember(dst => dst.WorkOrderAssignorPager, opt => opt.MapFrom(src => src.Assignee != null ? src.Assignee.Pager : null))
                .ForMember(dst => dst.WorkOrderAssignorPositionName, opt => opt.MapFrom(src => src.Assignee != null ? src.Assignee.PositionName : null))
                .ForMember(dst => dst.WorkOrderAssignorBuildingName, opt => opt.MapFrom(src => src.Assignee != null ? src.Assignee.BuildingName : null))
                .ForMember(dst => dst.WorkOrderAssignorRoomName, opt => opt.MapFrom(src => src.Assignee != null ? src.Assignee.RoomName : null))
                .ForMember(dst => dst.WorkOrderAssignorWorkplaceName, opt => opt.MapFrom(src => src.Assignee != null ? src.Assignee.WorkplaceName : null))
                .ForMember(dst => dst.WorkOrderAssignorOrganizationName, opt => opt.MapFrom(src => src.Assignee != null ? src.Assignee.OrganizationName : null))
                .ForMember(dst => dst.WorkOrderAssignorSubdivisionName, opt => opt.MapFrom(src => src.Assignee != null ? src.Assignee.SubdivisionName : null))
                .ForMember(dst => dst.WorkOrderExecutorLastName, opt => opt.MapFrom(src => src.Executor != null ? src.Executor.Surname : null))
                .ForMember(dst => dst.WorkOrderExecutorFirstName, opt => opt.MapFrom(src => src.Executor != null ? src.Executor.Name : null))
                .ForMember(dst => dst.WorkOrderExecutorPatronymic, opt => opt.MapFrom(src => src.Executor != null ? src.Executor.Patronymic : null))
                .ForMember(dst => dst.WorkOrderExecutorFullName, opt => opt.MapFrom(src => src.Executor != null ? src.Executor.FullName : null))
                .ForMember(dst => dst.WorkOrderExecutorLogin, opt => opt.MapFrom(src => src.Executor != null ? src.Executor.LoginName : null))
                .ForMember(dst => dst.WorkOrderExecutorPhone, opt => opt.MapFrom(src => src.Executor != null ? src.Executor.Phone : null))
                .ForMember(dst => dst.WorkOrderExecutorNumber, opt => opt.MapFrom(src => src.Executor != null ? src.Executor.Number : null))
                .ForMember(dst => dst.WorkOrderExecutorEmail, opt => opt.MapFrom(src => src.Executor != null ? src.Executor.Email : null))
                .ForMember(dst => dst.WorkOrderExecutorFax, opt => opt.MapFrom(src => src.Executor != null ? src.Executor.Fax : null))
                .ForMember(dst => dst.WorkOrderExecutorPager, opt => opt.MapFrom(src => src.Executor != null ? src.Executor.Pager : null))
                .ForMember(dst => dst.WorkOrderExecutorPositionName, opt => opt.MapFrom(src => src.Executor != null ? src.Executor.PositionName : null))
                .ForMember(dst => dst.WorkOrderExecutorBuildingName, opt => opt.MapFrom(src => src.Executor != null ? src.Executor.BuildingName : null))
                .ForMember(dst => dst.WorkOrderExecutorRoomName, opt => opt.MapFrom(src => src.Executor != null ? src.Executor.RoomName : null))
                .ForMember(dst => dst.WorkOrderExecutorWorkplaceName, opt => opt.MapFrom(src => src.Executor != null ? src.Executor.WorkplaceName : null))
                .ForMember(dst => dst.WorkOrderExecutorOrganizationName, opt => opt.MapFrom(src => src.Executor != null ? src.Executor.OrganizationName : null))
                .ForMember(dst => dst.WorkOrderExecutorSubdivisionName, opt => opt.MapFrom(src => src.Executor != null ? src.Executor.SubdivisionName : null))
                .ForMember(dst => dst.WorkOrderQueueName, opt => opt.MapFrom(src => src.Group != null ? src.Group.Name : null))
                .ForAllOtherMembers(o => o.Ignore())
                ;

            CreateMap<MassIncident, NegotiationTemplate>();
            
            CreateMap<DeputyUser, SubstitutionTemplate>()
                .ForMember(dst => dst.ChildName, opt => opt.MapFrom(src => src.Child == null ? null : src.Child.Name))
                .ForMember(dst => dst.ChildLastName, opt => opt.MapFrom(src => src.Child == null ? null : src.Child.Surname))
                .ForMember(dst => dst.ChildPatronymic, opt => opt.MapFrom(src => src.Child == null ? null : src.Child.Patronymic))
                .ForMember(dst => dst.ParentName, opt => opt.MapFrom(src => src.Parent == null ? null : src.Parent.Name))
                .ForMember(dst => dst.ParentLastName, opt => opt.MapFrom(src => src.Parent == null ? null : src.Parent.Surname))
                .ForMember(dst => dst.ParentPatronymic, opt => opt.MapFrom(src => src.Parent == null ? null : src.Parent.Patronymic))
                .ForMember(dst => dst.DateDeputyByString, opt => opt.MapFrom(src => src.UtcDataDeputyBy.ToString()))
                .ForMember(dst => dst.DateDeputyWithString, opt => opt.MapFrom(src => src.UtcDataDeputyWith.ToString()))
                ;
        }
    }
}
